### ISSUE TITLE
M5Stack Core2で音が出ない

### ISSUE THREAD

**Issue by dinosauria123** [suzukiplan/micro-msx2p#41]
/include/Audio.hppを音が出るよう書き換えました。ご査収ください。
[Audio.hpp.txt](https://github.com/suzukiplan/micro-msx2p/files/13112278/Audio.hpp.txt)

音なし、ボタン無効ですがM5Stack Basicでも動作してます。

M5Cardputerで動かすのが夢です！

**Comment by suzukiplan** [comment]
ありがとうございます！
後ほど確認します。

**Comment by suzukiplan** [comment]
すみません、確認しましたが M5Stack Core2 用のコードのようで、ご提供頂いたコードを適用すると M5Stack CoreS3 で動かなくなってしまいます。

[msx1-m5stackはドキュメント記載の通りCoreS3用](https://github.com/suzukiplan/micro-msx2p/blob/master/msx1-m5stack/README.md#m5stack-hardware)で、Core2はサポートしておりません。

Core2もサポートしたいのは山々なのですが、検証中にCore2が壊れてしまい、私の手元に検証できる端末が無いためCore2は非サポートとしています。

**Comment by suzukiplan** [comment]
余談ですが、M5CardputerはM5StampS3がコアだったと思うので、どちらかといえば[msx1-m5stamps3](https://github.com/suzukiplan/micro-msx2p/tree/master/msx1-m5stamps3)ベースで改造した方が動かしやすいかもしれません。（M5Cardputerは持っておらずあまり仕様を把握していないので自信ありませんが）

**Comment by dinosauria123** [comment]
ありがとうございます！Core2のサポートがもし将来あるようでしたらご参考になれば幸いです。

＞M5CardputerはM5StampS3がコアだったと思うので、どちらかといえば[msx1-m5stamps3](https://github.com/suzukiplan/micro-msx2p/tree/master/msx1-m5stamps3)ベースで改造した方が動かしやすいかもしれません。

そうおもいます。うまくいけばMSX0 Cloneができそうで楽しみです。

**Comment by suzukiplan** [comment]
Core2 サポートの際は参考にさせていただきます。
